### PR TITLE
Fix: Don't display measureTable when measures is empty

### PR DESCRIPTION
**Pull request by kagehina919**
Added patch for #335. 

I have added test for the same but the generated snapshot doesn't contain measureTable component. I've used mount instead of shallow rendering.

@wlach could you please help me with this?

### CODE REVIEW

**Comment by kagehina919** [comment]
@wlach The tests are failing as the promise required for [`this.props.fetchChannelPlatformSummaryData()`](https://github.com/mozilla/missioncontrol/blob/master/frontend/ui/subview.jsx#L63) is not being resolved until after the tests have run. 

I have tried to resolve it without using sinon, but it hasn't been successful. Should we setup `sinon` as suggested [here](https://github.com/airbnb/enzyme/issues/346#issuecomment-304535773)? 

Also, this function doesn't seem to do any updates in the state of `subView` as we are not using the returned value from calling [`this.props.fetchChannelPlatformSummaryData()`](https://github.com/mozilla/missioncontrol/blob/master/frontend/ui/subview.jsx#L63). Could you please tell me if this makes some changes to redux store? If not, then we can get away without using any promise for the test!

**Comment by kagehina919** [comment]
@wlach issue fixed. Please review.

**Comment by kagehina919** [comment]
@wlach could you please take a look at this? :sweat_smile:

**Comment by wlach** [comment]
Sorry! Was away for a week and away from a computer and forgot to let you
know, will take a look first thing tomorrow.

**Comment by wlach** [comment]
This looks and works great! I will merge.

**Pull request merged**
