### PR TITLE
Add celery queue + one simple task (to fetch version data)

### PR DESCRIPTION
**Pull request by wlach**

### CODE REVIEW

**Comment by wlach** [comment]
@robhudson would you mind taking a look at this when you have a moment? the celery config is based heavily on what was implemented for atmo.

**Comment by wlach** [comment]
I think we can merge this as-is, and get the appropriate containers running in production later.

**Comment by wlach** [comment]
@robotblake would you mind taking a look at this and let me know what you think from an ops perspective? There's not a lot of code yet so it should be pretty quick to look over. this is mostly the same setup as the one we have for atmo (3 containers -- 1 scheduler, 1 worker, 1 monitorer).

**Comment by whd** [comment]
At a minimum this needs to be rebased for a requirements conflict. I also had to run "yarn" manually before "make build" worked on my local box.

**Comment by wlach** [comment]
Let me fix the requirements conflict. The yarn stuff is documented in the README already, though maybe we could improve the build/make process to incorporate it by default.

**Comment by whd** [comment]
Ah, The README in https://github.com/wlach/missioncontrol/blob/celery/README.md does not have the updated instructions, which is what I was looking at.

**Comment by wlach** [comment]
Rebased on latest master.

**Comment by wlach** [comment]
Added some gitignore entries for celery stuff following atmo's example.

**Pull request merged**
